### ISSUE TITLE
🐛Bug: "Expand Code" on radiogroup does not work

### ISSUE THREAD

**Issue by alexbjorlig** [TGlide/radix-svelte#151]
**Describe the bug**
"Expand Code" on radiogroup does not work, [here](https://www.radix-svelte.com/docs/radiogroup).

![CleanShot 2023-05-22 at 09 56 48@2x](https://github.com/TGlide/radix-svelte/assets/9967422/5f59c105-6d61-436f-aaa9-0eb5c442e860)

**Comment by TGlide** [comment]
Thanks for raising the issue! Fixed on latest commits 😄
