### ISSUE TITLE
🐛Bug: alert-dialog: Background is scrollable on iOS Safari

### ISSUE THREAD

**Issue by multivac61** [TGlide/radix-svelte#158]
**Describe the bug**
Background should not be scrollable, independent of where I am on the screen when the dialog is opened. This is hard to get right on every device, [especially iOS Safari](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/overlays/src/usePreventScroll.ts#L80). 
 
https://user-images.githubusercontent.com/4436129/241951616-28336cdb-e33f-4d52-9d23-be501d872eb1.MP4

**To Reproduce**
1. Go to the alert-dialog using iOS Safari
2. Click on "Delete Account"
3. Scroll on the background
4. See error (background scrolling)

**Expected behavior**
Background should not be scrolling when modal is open.

**Screenshots**

See above videos.

**Smartphone (please complete the following information):**
- Device: iPhone 14 Pro 
- OS: iOS 16.4.1
 - Browser Safari
 - Version 16

**Comment by multivac61** [comment]
The least I can do! Your work is truly inspiring Thomas. Thank you for all your hard work, it is truly valuable 🙌

**Comment by TGlide** [comment]
@multivac61 would you mind testing if #159 solves this issue? Preview link: https://radix-svelte-qg1bwphtx-tglide.vercel.app/
