### ISSUE TITLE
⚙Tech Debt: Icons

### ISSUE THREAD

**Issue by SarcevicAntonio** [TGlide/radix-svelte#3]
I've noticed icons were generated as Svelte components. I propose we use [`unplugin-icons`](https://github.com/antfu/unplugin-icons) with [Iconify radix-icons](https://icon-sets.iconify.design/radix-icons/) or [`radix-icons-svelte`](https://www.npmjs.com/package/radix-icons-svelte) instead of dealing with it ourselves.

**Comment by TGlide** [comment]
Hmm, that may be a good idea. I'll look into it!

**Comment by stordahl** [comment]
+1 on adding `radix-icons-svelte` as a dep

**Comment by TGlide** [comment]
I'd rather go with unplugin-icons. It's constantly up-to-date, has other icon packs if we ever want to use them on the site, etc.

Either way is fine tbh, because this shouldn't be a dep of the actual package, just something we use on the site 🙂
