### ISSUE TITLE
✨ Component: Toast

### ISSUE THREAD

**Issue by TGlide** [TGlide/radix-svelte#33]
- [ ] Implementation
- [ ] Example
- [ ] Animation
- [ ] Storybook/Histoire
- [ ] Tests
- [ ] Docs

**Comment by SarcevicAntonio** [comment]
Hey, so I tried a bit yesterday, and it's way more difficult that I imagined.
I think my lack of experience with React and Radix makes me less suitable for the task than I realized.
What I'm saying is, don't count on me continuing this soon 👀
I'll take a look at other issues I could better help with when I find the time 😅

**Comment by TGlide** [comment]
@SarcevicAntonio hey no worries! It can be quite a lot.

If you want an easier component to start, you can take a look at label. An intermediate one would be radio group, especially since I've already done toggle group.

**Comment by hmnd** [comment]
@TGlide shouldn't this one still be open, since toasts aren't implemented yet :)

**Comment by TGlide** [comment]
> @TGlide shouldn't this issue still be open, since toasts aren't implemented yet :)

You're right! Re-opened 😄

**Comment by TGlide** [comment]
> @TGlide shouldn't this issue still be open, since toasts aren't implemented yet :)

Actually, I forgot I closed all component issues in favor of the readme roadmap. So closing again!
